//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS_Akura.UI
{
    public partial class CustomerPage
    {
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// btnNewCustomer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNewCustomer;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefresh;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// chkActiveOnly control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActiveOnly;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// litAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAlert;

        /// <summary>
        /// gvCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvCustomers;

        /// <summary>
        /// hfCustomerId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfCustomerId;

        /// <summary>
        /// hfAccountId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfAccountId;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtAccountCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountCode;

        /// <summary>
        /// txtAccountType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountType;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// chkIsActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
